services:
  rabbitmq:
    container_name: rabbit
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 10

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/server.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=server
      - PORT=12345
      - LISTEN_BACKLOG=1
      - HC_PORT=4321

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/client.dockerfile
    depends_on:
      - server
    links:
      - server
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=server
      - PORT=12345
      - TITLES_FILEPATH=./datasets/books_data.csv
      - REVIEWS_FILEPATH=./datasets/books_rating_sample.csv
    volumes:
      - ./datasets:/datasets

  query_coordinator_worker0:
    container_name: query_coordinator_worker0
    build:
      context: .
      dockerfile: ./query_coordinator/query_coordinator_worker.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - WORKERS_QUANTITY=1
      - WORKERS_Q1=3,QUEUE_Q1|filter_category_worker
      - WORKERS_Q2=3,QUEUE_Q2|decade_counter_worker
      - WORKERS_Q3_TITLES=3,QUEUE_Q3|filter_year_worker
      - WORKERS_Q3_REVIEWS=6,QUEUE_Q3|reviews_counter_worker_reviews
      - WORKERS_Q5_TITLES=3,QUEUE_Q5|filter_category_worker
      - WORKERS_Q5_REVIEWS=4,QUEUE_Q5|review_sentiment_worker
      - EOF_QUANTITY=3,1,1,1,1
      - HC_PORT=4321
      - ADDRESS=query_coordinator_worker0
      - PORT=4321

  container_coordinator_0:
    container_name: container_coordinator_0
    build:
      context: .
      dockerfile: ./container_coordinator/container_coordinator.dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - LISTEN_BACKLOG=10
      - ID=0
      - WORKERS_PORT=4321
      - WORKERS_QUANTITY=3
      - ADDRESS=container_coordinator_0
      - COORDS_PORT=1234
      - COORDS_LIST=container_coordinator_0,container_coordinator_1,container_coordinator_2

  container_coordinator_1:
    container_name: container_coordinator_1
    build:
      context: .
      dockerfile: ./container_coordinator/container_coordinator.dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - LISTEN_BACKLOG=10
      - ID=1
      - WORKERS_PORT=4321
      - WORKERS_QUANTITY=3
      - ADDRESS=container_coordinator_1
      - COORDS_PORT=1234
      - COORDS_LIST=container_coordinator_0,container_coordinator_1,container_coordinator_2

  container_coordinator_2:
    container_name: container_coordinator_2
    build:
      context: .
      dockerfile: ./container_coordinator/container_coordinator.dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - LISTEN_BACKLOG=10
      - ID=2
      - WORKERS_PORT=4321
      - WORKERS_QUANTITY=3
      - ADDRESS=container_coordinator_2
      - COORDS_PORT=1234
      - COORDS_LIST=container_coordinator_0,container_coordinator_1,container_coordinator_2

  
