version: '3'
services:

  rabbitmq:
    container_name: rabbit
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10

  producer:
    build:
      context: .
      dockerfile: ./producer/producer.dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=server
      - PORT=12345
      - LISTEN_BACKLOG=1

  #consumer:
  #  build:
  #    context: .
  #    dockerfile: ./consumer/consumer.dockerfile
  #  depends_on:
  #    - rabbitmq
  #  links: 
  #    - rabbitmq
  #  environment:
  #    - PYTHONUNBUFFERED=1
  #    - HOST=server
  #    - PORT=12345
  #    - LISTEN_BACKLOG=1



  #server:
  #  container_name: server
  #  build:
  #    context: .
  #    dockerfile: ./server/server.dockerfile
  #  depends_on:
  #    - rabbitmq
  #  links: 
  #    - rabbitmq
  #  environment:
  #    - PYTHONUNBUFFERED=1
  #    - HOST=server
  #    - PORT=12345
  #    - LISTEN_BACKLOG=1
  #  volumes:
  #    - ./datasets:/datasets
#
  #client:
  #  container_name: client
  #  build:
  #    context: .
  #    dockerfile: ./client/client.dockerfile
  #  depends_on:
  #    - server
  #  links: 
  #    - server
  #  environment:
  #    - PYTHONUNBUFFERED=1
  #    - HOST=server
  #    - PORT=12345
  #    - TITLES_FILEPATH=./datasets/books_data.csv
  #    - REVIEWS_FILEPATH=./datasets/books_rating_sample.csv
  #  volumes:
  #    - ./datasets:/datasets
#
  ##filter_category_worker:
  ##  container_name: filter_category_worker
  #  build:
  #    context: .
  #    dockerfile: ./workers_dockerfiles/filter_category_worker.dockerfile
  #  depends_on:
  #    - rabbitmq
  #  links: 
  #    - rabbitmq
  #  environment:
  #    - PYTHONUNBUFFERED=1
  #    - CATEGORY=Computers
  #    - DATA_SOURCE_NAME=titles
  #    - DATA_OUTPUT_NAME=Q1|filter_title_worker
  #  volumes:
  #    - ./datasets:/datasets
#
  #filter_title_worker:
  #  container_name: filter_title_worker
  #  build:
  #    context: .
  #    dockerfile: ./workers_dockerfiles/filter_title_worker.dockerfile
  #  depends_on:
  #    - rabbitmq
  #  links: 
  #    - rabbitmq
  #  environment:
  #    - PYTHONUNBUFFERED=1
  #    - TITLE_TO_FILTER=distributed
  #    - DATA_SOURCE_NAME=Q1|filter_title_worker
  #    - DATA_OUTPUT_NAME=Q1|filter_year_worker
  #
  #filter_year_worker:
  #  container_name: filter_year_worker
  #  build:
  #    context: .
  #    dockerfile: ./workers_dockerfiles/filter_year_worker.dockerfile
  #  depends_on:
  #    - rabbitmq
  #  links: 
  #    - rabbitmq
  #  environment:
  #    - PYTHONUNBUFFERED=1
  #    - YEAR_RANGE_TO_FILTER=2000,2023
  #    - DATA_SOURCE_NAME=Q1|filter_year_worker
  #    - DATA_OUTPUT_NAME=Q1|server
  #    
  #decade_counter_worker:
  #  container_name: decade_counter_worker
  #  build:
  #    context: .
  #    dockerfile: ./workers_dockerfiles/decade_counter_worker.dockerfile
  #  depends_on:
  #    - rabbitmq
  #  links: 
  #    - rabbitmq
  #  environment:
  #    - PYTHONUNBUFFERED=1
  #    - DATA_SOURCE_NAME=titles
  #    - DATA_OUTPUT_NAME=Q2|global_decade_counter_worker
#
  #global_decade_counter_worker:
  #  container_name: global_decade_counter_worker
  #  build:
  #    context: .
  #    dockerfile: ./workers_dockerfiles/global_decade_counter_worker.dockerfile
  #  depends_on:
  #    - rabbitmq
  #  links: 
  #    - rabbitmq
  #  environment:
  #    - PYTHONUNBUFFERED=1
  #    - DATA_SOURCE_NAME=Q2|global_decade_counter_worker
  #    - DATA_OUTPUT_NAME=server
