services:
  rabbitmq:
    container_name: rabbit
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 10

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/server.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=server
      - PORT=12345
      - LISTEN_BACKLOG=1

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/client.dockerfile
    depends_on:
      - server
    links:
      - server
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=server
      - PORT=12345
      - TITLES_FILEPATH=./datasets/books_data.csv
      - REVIEWS_FILEPATH=./datasets/books_rating_sample.csv
    volumes:
      - ./datasets:/datasets

  query_coordinator_worker:
    container_name: query_coordinator_worker
    build:
      context: .
      dockerfile: ./query_coordinator/query_coordinator_worker.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - EOF_TITLES_MAX_SUBS=6
      - EOF_REVIEWS_MAX_SUBS=6
      - WORKERS_Q1=3
      - WORKERS_Q2=3
      - WORKERS_Q3_TITLES=3
      - WORKERS_Q3_REVIEWS=3
      - WORKERS_Q5_TITLES=3
      - WORKERS_Q5_REVIEWS=4

  filter_category_computers_worker0:
    container_name: filter_category_computers_worker0
    build:
      context: .
      dockerfile: ./workers_dockerfiles/filter_category_worker.dockerfile
    environment:
      - WORKER_ID=0
      - NEXT_WORKER_QUANTITY=3
      - WORKERS_QUANTITY=3
      - CATEGORY=Computers
      - DATA_SOURCE_NAME=QUEUE_Q1|filter_category_worker
      - DATA_OUTPUT_NAME=QUEUE_Q1|filter_title_worker
      - EOF_QUEUE=QUEUE_Q1|eof_category
      - ITERATION_QUEUE=QUEUE_Q1|iteration_category
  filter_category_computers_worker1:
    container_name: filter_category_computers_worker1
    build:
      context: .
      dockerfile: ./workers_dockerfiles/filter_category_worker.dockerfile
    environment:
      - WORKER_ID=1
      - NEXT_WORKER_QUANTITY=3
      - WORKERS_QUANTITY=3
      - CATEGORY=Computers
      - DATA_SOURCE_NAME=QUEUE_Q1|filter_category_worker
      - DATA_OUTPUT_NAME=QUEUE_Q1|filter_title_worker
      - EOF_QUEUE=QUEUE_Q1|eof_category
      - ITERATION_QUEUE=QUEUE_Q1|iteration_category
  filter_category_computers_worker2:
    container_name: filter_category_computers_worker2
    build:
      context: .
      dockerfile: ./workers_dockerfiles/filter_category_worker.dockerfile
    environment:
      - WORKER_ID=2
      - NEXT_WORKER_QUANTITY=3
      - WORKERS_QUANTITY=3
      - CATEGORY=Computers
      - DATA_SOURCE_NAME=QUEUE_Q1|filter_category_worker
      - DATA_OUTPUT_NAME=QUEUE_Q1|filter_title_worker
      - EOF_QUEUE=QUEUE_Q1|eof_category
      - ITERATION_QUEUE=QUEUE_Q1|iteration_category
  filter_title_worker0:
    container_name: filter_title_worker0
    build:
      context: .
      dockerfile: ./workers_dockerfiles/filter_title_worker.dockerfile
    environment:
      - WORKER_ID=0
      - NEXT_WORKER_QUANTITY=3
      - WORKERS_QUANTITY=3
      - TITLE_TO_FILTER=distributed
      - DATA_SOURCE_NAME=QUEUE_Q1|filter_title_worker
      - DATA_OUTPUT_NAME=QUEUE_Q1|filter_year_worker
      - EOF_QUEUE=QUEUE_Q1|eof_title
      - ITERATION_QUEUE=QUEUE_Q1|iteration_title
  filter_title_worker1:
    container_name: filter_title_worker1
    build:
      context: .
      dockerfile: ./workers_dockerfiles/filter_title_worker.dockerfile
    environment:
      - WORKER_ID=1
      - NEXT_WORKER_QUANTITY=3
      - WORKERS_QUANTITY=3
      - TITLE_TO_FILTER=distributed
      - DATA_SOURCE_NAME=QUEUE_Q1|filter_title_worker
      - DATA_OUTPUT_NAME=QUEUE_Q1|filter_year_worker
      - EOF_QUEUE=QUEUE_Q1|eof_title
      - ITERATION_QUEUE=QUEUE_Q1|iteration_title
  filter_title_worker2:
    container_name: filter_title_worker2
    build:
      context: .
      dockerfile: ./workers_dockerfiles/filter_title_worker.dockerfile
    environment:
      - WORKER_ID=2
      - NEXT_WORKER_QUANTITY=3
      - WORKERS_QUANTITY=3
      - TITLE_TO_FILTER=distributed
      - DATA_SOURCE_NAME=QUEUE_Q1|filter_title_worker
      - DATA_OUTPUT_NAME=QUEUE_Q1|filter_year_worker
      - EOF_QUEUE=QUEUE_Q1|eof_title
      - ITERATION_QUEUE=QUEUE_Q1|iteration_title
  filter_year_worker_q1-0:
    container_name: filter_year_worker_q1-0
    build:
      context: .
      dockerfile: ./workers_dockerfiles/filter_year_worker.dockerfile
    environment:
      - WORKER_ID=0
      - NEXT_WORKER_QUANTITY=1
      - WORKERS_QUANTITY=3
      - YEAR_RANGE_TO_FILTER=2000,2023
      - DATA_SOURCE_NAME=QUEUE_Q1|filter_year_worker
      - DATA_OUTPUT_NAME=QUEUE_q1_results
      - EOF_QUEUE=QUEUE_Q1|eof_year
      - END=True
      - ITERATION_QUEUE=QUEUE_Q1|iteration_year
  filter_year_worker_q1-1:
    container_name: filter_year_worker_q1-1
    build:
      context: .
      dockerfile: ./workers_dockerfiles/filter_year_worker.dockerfile
    environment:
      - WORKER_ID=1
      - NEXT_WORKER_QUANTITY=1
      - WORKERS_QUANTITY=3
      - YEAR_RANGE_TO_FILTER=2000,2023
      - DATA_SOURCE_NAME=QUEUE_Q1|filter_year_worker
      - DATA_OUTPUT_NAME=QUEUE_q1_results
      - EOF_QUEUE=QUEUE_Q1|eof_year
      - END=True
      - ITERATION_QUEUE=QUEUE_Q1|iteration_year
  filter_year_worker_q1-2:
    container_name: filter_year_worker_q1-2
    build:
      context: .
      dockerfile: ./workers_dockerfiles/filter_year_worker.dockerfile
    environment:
      - WORKER_ID=2
      - NEXT_WORKER_QUANTITY=1
      - WORKERS_QUANTITY=3
      - YEAR_RANGE_TO_FILTER=2000,2023
      - DATA_SOURCE_NAME=QUEUE_Q1|filter_year_worker
      - DATA_OUTPUT_NAME=QUEUE_q1_results
      - EOF_QUEUE=QUEUE_Q1|eof_year
      - END=True
      - ITERATION_QUEUE=QUEUE_Q1|iteration_year