services:
  rabbitmq:
    container_name: rabbit
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 10

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/server.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=server
      - PORT=12345
      - LISTEN_BACKLOG=1

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/client.dockerfile
    depends_on:
      - server
    links:
      - server
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=server
      - PORT=12345
      - TITLES_FILEPATH=./datasets/books_data.csv
      - REVIEWS_FILEPATH=./datasets/books_rating_sample-0.02.csv
    volumes:
      - ./datasets:/datasets

  query_coordinator_worker:
    container_name: query_coordinator_worker
    build:
      context: .
      dockerfile: ./query_coordinator/query_coordinator_worker.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - EOF_TITLES_MAX_SUBS=6
      - EOF_REVIEWS_MAX_SUBS=6
      - WORKERS_Q1=3
      - WORKERS_Q2=3
      - WORKERS_Q3_TITLES=3
      - WORKERS_Q3_REVIEWS=3
      - WORKERS_Q5_TITLES=3
      - WORKERS_Q5_REVIEWS=4
